package rules

rule "Create ReadSet Nanopore CNG"
	@nglBI(F_S_1)
	@nglSQ(F_S_1)
	dialect "java"
	salience 700
	no-loop
	when  
		$run:Run(categoryCode=="nanopore")
		$container:Container(support.code==$run.containerSupportCode,$contents:contents)
		$content:Content() from $contents
		$contextError:ContextValidation()
	then
		Logger.debug("ReadSet Creation for run "+$run.code);
		//Creation des readsets
 		Date runStartDate =  $run.sequencingStartDate;

  		// 23/03/2022 NGL-3793 le projet "CNG_CONTROL_0" ne suit pas la règle <NOM>_<NUM> => il  a 2 "_" !!! 
 		// String shortProjectCode = $content.projectCode.charAt(0)+$content.projectCode.split("_",2)[1];
 		String[] part=$content.projectCode.split("_");
 		String shortProjectCode = $content.projectCode.charAt(0)+$content.projectCode.split("_")[part.length -1];
 		Logger.debug("shortProjectCode="+shortProjectCode);
 		
		String codeReadSet = shortProjectCode+"_ONT_"+$content.sampleCode+"_"+$container.support.line+"_"+$run.containerSupportCode;
 		List<ReadSet> readSets = MongoDBDAO.find(InstanceConstants.READSET_ILLUMINA_COLL_NAME, ReadSet.class,  DBQuery.is("code",codeReadSet)).toList();
 		if(readSets.size()==0){
			ReadSet readSet=new ReadSet();
			readSet.typeCode="rsnanopore";
			readSet.code=codeReadSet;
			
			if($content.properties.containsKey("tag")){
				String tag = $content.properties.get("tag").value.toString();
				Index index=MongoDBDAO.findOne(InstanceConstants.PARAMETER_COLL_NAME, Index.class, DBQuery.in("typeCode", "index-nanopore-sequencing").is("code", tag));
				readSet.code=readSet.code+"."+index.shortName;
			}
		
			readSet.state=new State("N","ngsrg");
			readSet.submissionState = new State("NONE", "ngsrg");
		
			readSet.runCode=$run.code;
			readSet.runTypeCode=$run.typeCode;
			readSet.runSequencingStartDate=runStartDate;
			readSet.laneNumber=new Integer($container.support.line);
			readSet.sampleCode=$content.sampleCode;
			readSet.projectCode=$content.projectCode;
			//TO DO
			readSet.path="A_RENSEIGNER";
     		readSet.location="CNRGH";	
			readSet.traceInformation=new TraceInformation();
			readSet.traceInformation.setTraceInformation("ngsrg");
					
	    	ContextValidation localContextError = ContextValidation.createCreationContext("nsgrg");
			localContextError.setContextObjects($contextError.getContextObjects());
	    	InstanceHelpers.save(InstanceConstants.READSET_ILLUMINA_COLL_NAME,readSet,localContextError,true);
	    	MongoDBDAO.update(InstanceConstants.RUN_ILLUMINA_COLL_NAME, Run.class
					,DBQuery.is("code",$run.code)
					,DBUpdate.addToSet("sampleCodes", $content.sampleCode).addToSet("projectCodes",$content.projectCode));
			}
	    
end

