package controllers.instruments.io.cng.miseqqcmode;

import fr.cea.ig.ngl.dao.api.factory.propertyfilevalue.PropertyFileValueFactory;
import models.laboratory.common.instance.property.PropertyFileValue;

public final class MultiInputTestHelper {
	
	private MultiInputTestHelper() {}
	
	public static final PropertyFileValue getSummaryHtmFile() {
		return PropertyFileValueFactory.getRandomPropertyFileValue("Summary.htm",
				"<html>\r\n"
				+ "  <body>\r\n"
				+ "    <h1>Summary Information For Experiment 201103_MISEQ2_0189_000000000-J98GY</h1>\r\n"
				+ "    <h2>Chip Summary</h2>\r\n"
				+ "    <table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Machine</td>\r\n"
				+ "        <td>M04179</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Run Folder</td>\r\n"
				+ "        <td>201103_MISEQ2_0189_000000000-J98GY</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Chip ID</td>\r\n"
				+ "        <td>000000000-J98GY</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "    <h2>Chip Results Summary</h2>\r\n"
				+ "    <table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Clusters</td>\r\n"
				+ "        <td>Clusters (PF)</td>\r\n"
				+ "        <td>Yield (kbases)</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>10007482</td>\r\n"
				+ "        <td>9644803</td>\r\n"
				+ "        <td>1466010</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "    <h2>Lane Parameter Summary</h2>\r\n"
				+ "    <table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Lane </td>\r\n"
				+ "        <td>Sample ID</td>\r\n"
				+ "        <td>Sample Target</td>\r\n"
				+ "        <td>Length</td>\r\n"
				+ "        <td>Tile count</td>\r\n"
				+ "        <td>Tiles</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>multiple</td>\r\n"
				+ "        <td>D:\\Genomes\\Homo_sapiens\\UCSC\\hg19\\Sequence\\WholeGenomeFasta</td>\r\n"
				+ "        <td>76,76</td>\r\n"
				+ "        <td>38</td>\r\n"
				+ "        <td><a href=\"#Lane1\">\r\n"
				+ "        Lane 1</a></td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "    <h2>Lane Results Summary : Read 1</h2>\r\n"
				+ "    <table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"2\">Lane Info</td>\r\n"
				+ "        <td colspan=\"8\">Tile Mean ± SD for Lane</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Lane </td>\r\n"
				+ "        <td>Lane Yield (kbases) </td>\r\n"
				+ "        <td>Clusters (raw)</td>\r\n"
				+ "        <td>Clusters (PF) </td>\r\n"
				+ "        <td>1st Cycle Int (PF) </td>\r\n"
				+ "        <td>% intensity after 20 cycles (PF) </td>\r\n"
				+ "        <td>% PF Clusters </td>\r\n"
				+ "        <td>% Align (PF) </td>\r\n"
				+ "        <td>Alignment Score (PF) </td>\r\n"
				+ "        <td>% Mismatch Rate (PF) </td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1466010</td>\r\n"
				+ "        <td>263355 ± 10894</td>\r\n"
				+ "        <td>253811 ± 8655</td>\r\n"
				+ "        <td>112.9 ± 5.8</td>\r\n"
				+ "        <td>95.0 ± 1.8</td>\r\n"
				+ "        <td>96.41 ± 0.76</td>\r\n"
				+ "        <td>0.00 ± 0.00</td>\r\n"
				+ "        <td>0.00 ± 0.00</td>\r\n"
				+ "        <td>0.00 ± 0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"13\">Tile mean across chip</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"2\">Average</td>\r\n"
				+ "        <td>263355</td>\r\n"
				+ "        <td>253811</td>\r\n"
				+ "        <td>113</td>\r\n"
				+ "        <td>94.95</td>\r\n"
				+ "        <td>96.41</td>\r\n"
				+ "        <td>0</td>\r\n"
				+ "        <td>0</td>\r\n"
				+ "        <td>0</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "    <h2>Lane Results Summary : Read 2</h2>\r\n"
				+ "    <table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"2\">Lane Info</td>\r\n"
				+ "        <td colspan=\"8\">Tile Mean ± SD for Lane</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Lane </td>\r\n"
				+ "        <td>Lane Yield (kbases) </td>\r\n"
				+ "        <td>Clusters (raw)</td>\r\n"
				+ "        <td>Clusters (PF) </td>\r\n"
				+ "        <td>1st Cycle Int (PF) </td>\r\n"
				+ "        <td>% intensity after 20 cycles (PF) </td>\r\n"
				+ "        <td>% PF Clusters </td>\r\n"
				+ "        <td>% Align (PF) </td>\r\n"
				+ "        <td>Alignment Score (PF) </td>\r\n"
				+ "        <td>% Mismatch Rate (PF) </td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1466010</td>\r\n"
				+ "        <td>263355 ± 10894</td>\r\n"
				+ "        <td>253811 ± 8655</td>\r\n"
				+ "        <td>125.2 ± 7.4</td>\r\n"
				+ "        <td>91.7 ± 1.5</td>\r\n"
				+ "        <td>96.41 ± 0.76</td>\r\n"
				+ "        <td>0.00 ± 0.00</td>\r\n"
				+ "        <td>0.00 ± 0.00</td>\r\n"
				+ "        <td>0.00 ± 0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"13\">Tile mean across chip</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"2\">Average</td>\r\n"
				+ "        <td>263355</td>\r\n"
				+ "        <td>253811</td>\r\n"
				+ "        <td>125</td>\r\n"
				+ "        <td>91.68</td>\r\n"
				+ "        <td>96.41</td>\r\n"
				+ "        <td>0</td>\r\n"
				+ "        <td>0</td>\r\n"
				+ "        <td>0</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "    <h2>Expanded Lane Summary : Read 1</h2>\r\n"
				+ "    <table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"2\">Lane Info</td>\r\n"
				+ "        <td colspan=\"2\">Phasing Info</td>\r\n"
				+ "        <td colspan=\"1\">Raw Data (tile mean)</td>\r\n"
				+ "        <td colspan=\"5\">Filtered Data (tile mean)</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Lane </td>\r\n"
				+ "        <td>Clusters (tile mean) (raw) </td>\r\n"
				+ "        <td>% Phasing </td>\r\n"
				+ "        <td>% Prephasing </td>\r\n"
				+ "        <td>% retained </td>\r\n"
				+ "        <td>Cycle 2-4 Av Int (PF) </td>\r\n"
				+ "        <td>Cycle 2-10 Av % Loss (PF) </td>\r\n"
				+ "        <td>Cycle 10-20 Av % Loss (PF) </td>\r\n"
				+ "        <td>% Align (PF) </td>\r\n"
				+ "        <td>% Mismatch Rate (PF) </td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>263355</td>\r\n"
				+ "        <td>0.1379</td>\r\n"
				+ "        <td>0.0816</td>\r\n"
				+ "        <td>96.41</td>\r\n"
				+ "        <td>253 ± 13</td>\r\n"
				+ "        <td>0.20 ± 0.2</td>\r\n"
				+ "        <td>0.04 ± 0.1</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "    <h2>Expanded Lane Summary : Read 2</h2>\r\n"
				+ "    <table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"2\">Lane Info</td>\r\n"
				+ "        <td colspan=\"2\">Phasing Info</td>\r\n"
				+ "        <td colspan=\"1\">Raw Data (tile mean)</td>\r\n"
				+ "        <td colspan=\"5\">Filtered Data (tile mean)</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>Lane </td>\r\n"
				+ "        <td>Clusters (tile mean) (raw) </td>\r\n"
				+ "        <td>% Phasing </td>\r\n"
				+ "        <td>% Prephasing </td>\r\n"
				+ "        <td>% retained </td>\r\n"
				+ "        <td>Cycle 2-4 Av Int (PF) </td>\r\n"
				+ "        <td>Cycle 2-10 Av % Loss (PF) </td>\r\n"
				+ "        <td>Cycle 10-20 Av % Loss (PF) </td>\r\n"
				+ "        <td>% Align (PF) </td>\r\n"
				+ "        <td>% Mismatch Rate (PF) </td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>263355</td>\r\n"
				+ "        <td>0.0960</td>\r\n"
				+ "        <td>0.0380</td>\r\n"
				+ "        <td>96.41</td>\r\n"
				+ "        <td>276 ± 17</td>\r\n"
				+ "        <td>0.21 ± 0.2</td>\r\n"
				+ "        <td>0.00 ± 0.1</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table><a name=\"Lane1\"><h2>Lane 1 : Read 1</h2></a><table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"1\">Lane </td>\r\n"
				+ "        <td colspan=\"1\">Tile</td>\r\n"
				+ "        <td colspan=\"1\">Clusters (raw)</td>\r\n"
				+ "        <td colspan=\"1\">Av 1st Cycle Int (PF)</td>\r\n"
				+ "        <td colspan=\"1\">Av % intensity after 20 cycles (PF)</td>\r\n"
				+ "        <td colspan=\"1\">% PF Clusters </td>\r\n"
				+ "        <td colspan=\"1\">% Align (PF) </td>\r\n"
				+ "        <td colspan=\"1\">Av Alignment Score (PF)</td>\r\n"
				+ "        <td colspan=\"1\">% Mismatch Rate (PF) </td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1101</td>\r\n"
				+ "        <td>272722</td>\r\n"
				+ "        <td>113</td>\r\n"
				+ "        <td>97.35</td>\r\n"
				+ "        <td>95.78</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1102</td>\r\n"
				+ "        <td>273756</td>\r\n"
				+ "        <td>119</td>\r\n"
				+ "        <td>92.44</td>\r\n"
				+ "        <td>95.68</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1103</td>\r\n"
				+ "        <td>271950</td>\r\n"
				+ "        <td>118</td>\r\n"
				+ "        <td>93.22</td>\r\n"
				+ "        <td>95.80</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1104</td>\r\n"
				+ "        <td>271878</td>\r\n"
				+ "        <td>112</td>\r\n"
				+ "        <td>93.75</td>\r\n"
				+ "        <td>95.63</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1105</td>\r\n"
				+ "        <td>270956</td>\r\n"
				+ "        <td>118</td>\r\n"
				+ "        <td>93.22</td>\r\n"
				+ "        <td>95.69</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1106</td>\r\n"
				+ "        <td>271612</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>94.02</td>\r\n"
				+ "        <td>95.80</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1107</td>\r\n"
				+ "        <td>271852</td>\r\n"
				+ "        <td>114</td>\r\n"
				+ "        <td>92.98</td>\r\n"
				+ "        <td>95.63</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1108</td>\r\n"
				+ "        <td>272706</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>92.31</td>\r\n"
				+ "        <td>95.46</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1109</td>\r\n"
				+ "        <td>272292</td>\r\n"
				+ "        <td>118</td>\r\n"
				+ "        <td>94.92</td>\r\n"
				+ "        <td>95.80</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1110</td>\r\n"
				+ "        <td>272198</td>\r\n"
				+ "        <td>120</td>\r\n"
				+ "        <td>95.83</td>\r\n"
				+ "        <td>95.84</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1111</td>\r\n"
				+ "        <td>273352</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>97.44</td>\r\n"
				+ "        <td>95.81</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1112</td>\r\n"
				+ "        <td>274104</td>\r\n"
				+ "        <td>119</td>\r\n"
				+ "        <td>96.64</td>\r\n"
				+ "        <td>95.74</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1113</td>\r\n"
				+ "        <td>274169</td>\r\n"
				+ "        <td>116</td>\r\n"
				+ "        <td>97.41</td>\r\n"
				+ "        <td>95.65</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1114</td>\r\n"
				+ "        <td>275033</td>\r\n"
				+ "        <td>121</td>\r\n"
				+ "        <td>95.04</td>\r\n"
				+ "        <td>95.56</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1115</td>\r\n"
				+ "        <td>275351</td>\r\n"
				+ "        <td>122</td>\r\n"
				+ "        <td>93.44</td>\r\n"
				+ "        <td>94.98</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1116</td>\r\n"
				+ "        <td>276082</td>\r\n"
				+ "        <td>121</td>\r\n"
				+ "        <td>97.52</td>\r\n"
				+ "        <td>95.79</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1117</td>\r\n"
				+ "        <td>276770</td>\r\n"
				+ "        <td>120</td>\r\n"
				+ "        <td>95.83</td>\r\n"
				+ "        <td>95.62</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1118</td>\r\n"
				+ "        <td>278261</td>\r\n"
				+ "        <td>122</td>\r\n"
				+ "        <td>95.90</td>\r\n"
				+ "        <td>95.63</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1119</td>\r\n"
				+ "        <td>277348</td>\r\n"
				+ "        <td>122</td>\r\n"
				+ "        <td>97.54</td>\r\n"
				+ "        <td>95.63</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2101</td>\r\n"
				+ "        <td>250389</td>\r\n"
				+ "        <td>105</td>\r\n"
				+ "        <td>95.24</td>\r\n"
				+ "        <td>97.08</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2102</td>\r\n"
				+ "        <td>249361</td>\r\n"
				+ "        <td>106</td>\r\n"
				+ "        <td>94.34</td>\r\n"
				+ "        <td>97.07</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2103</td>\r\n"
				+ "        <td>248080</td>\r\n"
				+ "        <td>106</td>\r\n"
				+ "        <td>94.34</td>\r\n"
				+ "        <td>97.01</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2104</td>\r\n"
				+ "        <td>249519</td>\r\n"
				+ "        <td>105</td>\r\n"
				+ "        <td>95.24</td>\r\n"
				+ "        <td>97.20</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2105</td>\r\n"
				+ "        <td>248910</td>\r\n"
				+ "        <td>105</td>\r\n"
				+ "        <td>95.24</td>\r\n"
				+ "        <td>97.19</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2106</td>\r\n"
				+ "        <td>249358</td>\r\n"
				+ "        <td>108</td>\r\n"
				+ "        <td>87.96</td>\r\n"
				+ "        <td>97.16</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2107</td>\r\n"
				+ "        <td>249622</td>\r\n"
				+ "        <td>106</td>\r\n"
				+ "        <td>89.62</td>\r\n"
				+ "        <td>97.12</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2108</td>\r\n"
				+ "        <td>250222</td>\r\n"
				+ "        <td>108</td>\r\n"
				+ "        <td>89.81</td>\r\n"
				+ "        <td>97.04</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2109</td>\r\n"
				+ "        <td>251525</td>\r\n"
				+ "        <td>109</td>\r\n"
				+ "        <td>92.66</td>\r\n"
				+ "        <td>97.04</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2110</td>\r\n"
				+ "        <td>251130</td>\r\n"
				+ "        <td>107</td>\r\n"
				+ "        <td>94.39</td>\r\n"
				+ "        <td>97.24</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2111</td>\r\n"
				+ "        <td>251885</td>\r\n"
				+ "        <td>109</td>\r\n"
				+ "        <td>92.66</td>\r\n"
				+ "        <td>97.18</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2112</td>\r\n"
				+ "        <td>253172</td>\r\n"
				+ "        <td>110</td>\r\n"
				+ "        <td>92.73</td>\r\n"
				+ "        <td>97.17</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2113</td>\r\n"
				+ "        <td>255131</td>\r\n"
				+ "        <td>109</td>\r\n"
				+ "        <td>91.74</td>\r\n"
				+ "        <td>97.11</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2114</td>\r\n"
				+ "        <td>254758</td>\r\n"
				+ "        <td>106</td>\r\n"
				+ "        <td>94.34</td>\r\n"
				+ "        <td>97.09</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2115</td>\r\n"
				+ "        <td>257279</td>\r\n"
				+ "        <td>110</td>\r\n"
				+ "        <td>94.55</td>\r\n"
				+ "        <td>97.05</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2116</td>\r\n"
				+ "        <td>256711</td>\r\n"
				+ "        <td>108</td>\r\n"
				+ "        <td>95.37</td>\r\n"
				+ "        <td>97.27</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2117</td>\r\n"
				+ "        <td>258605</td>\r\n"
				+ "        <td>109</td>\r\n"
				+ "        <td>93.58</td>\r\n"
				+ "        <td>97.24</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2118</td>\r\n"
				+ "        <td>259412</td>\r\n"
				+ "        <td>108</td>\r\n"
				+ "        <td>93.52</td>\r\n"
				+ "        <td>97.28</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2119</td>\r\n"
				+ "        <td>260021</td>\r\n"
				+ "        <td>109</td>\r\n"
				+ "        <td>94.50</td>\r\n"
				+ "        <td>97.36</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table><a name=\"Lane1\"><h2>Lane 1 : Read 2</h2></a><table border=\"1\" cellpadding=\"5\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td colspan=\"1\">Lane </td>\r\n"
				+ "        <td colspan=\"1\">Tile</td>\r\n"
				+ "        <td colspan=\"1\">Clusters (raw)</td>\r\n"
				+ "        <td colspan=\"1\">Av 1st Cycle Int (PF)</td>\r\n"
				+ "        <td colspan=\"1\">Av % intensity after 20 cycles (PF)</td>\r\n"
				+ "        <td colspan=\"1\">% PF Clusters </td>\r\n"
				+ "        <td colspan=\"1\">% Align (PF) </td>\r\n"
				+ "        <td colspan=\"1\">Av Alignment Score (PF)</td>\r\n"
				+ "        <td colspan=\"1\">% Mismatch Rate (PF) </td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1101</td>\r\n"
				+ "        <td>272722</td>\r\n"
				+ "        <td>128</td>\r\n"
				+ "        <td>93.75</td>\r\n"
				+ "        <td>95.78</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1102</td>\r\n"
				+ "        <td>273756</td>\r\n"
				+ "        <td>128</td>\r\n"
				+ "        <td>95.31</td>\r\n"
				+ "        <td>95.68</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1103</td>\r\n"
				+ "        <td>271950</td>\r\n"
				+ "        <td>131</td>\r\n"
				+ "        <td>94.66</td>\r\n"
				+ "        <td>95.80</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1104</td>\r\n"
				+ "        <td>271878</td>\r\n"
				+ "        <td>129</td>\r\n"
				+ "        <td>93.80</td>\r\n"
				+ "        <td>95.63</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1105</td>\r\n"
				+ "        <td>270956</td>\r\n"
				+ "        <td>131</td>\r\n"
				+ "        <td>92.37</td>\r\n"
				+ "        <td>95.69</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1106</td>\r\n"
				+ "        <td>271612</td>\r\n"
				+ "        <td>133</td>\r\n"
				+ "        <td>92.48</td>\r\n"
				+ "        <td>95.80</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1107</td>\r\n"
				+ "        <td>271852</td>\r\n"
				+ "        <td>133</td>\r\n"
				+ "        <td>91.73</td>\r\n"
				+ "        <td>95.63</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1108</td>\r\n"
				+ "        <td>272706</td>\r\n"
				+ "        <td>132</td>\r\n"
				+ "        <td>92.42</td>\r\n"
				+ "        <td>95.46</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1109</td>\r\n"
				+ "        <td>272292</td>\r\n"
				+ "        <td>134</td>\r\n"
				+ "        <td>93.28</td>\r\n"
				+ "        <td>95.80</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1110</td>\r\n"
				+ "        <td>272198</td>\r\n"
				+ "        <td>133</td>\r\n"
				+ "        <td>93.23</td>\r\n"
				+ "        <td>95.84</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1111</td>\r\n"
				+ "        <td>273352</td>\r\n"
				+ "        <td>134</td>\r\n"
				+ "        <td>92.54</td>\r\n"
				+ "        <td>95.81</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1112</td>\r\n"
				+ "        <td>274104</td>\r\n"
				+ "        <td>134</td>\r\n"
				+ "        <td>93.28</td>\r\n"
				+ "        <td>95.74</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1113</td>\r\n"
				+ "        <td>274169</td>\r\n"
				+ "        <td>133</td>\r\n"
				+ "        <td>93.98</td>\r\n"
				+ "        <td>95.65</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1114</td>\r\n"
				+ "        <td>275033</td>\r\n"
				+ "        <td>134</td>\r\n"
				+ "        <td>93.28</td>\r\n"
				+ "        <td>95.56</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1115</td>\r\n"
				+ "        <td>275351</td>\r\n"
				+ "        <td>136</td>\r\n"
				+ "        <td>92.65</td>\r\n"
				+ "        <td>94.98</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1116</td>\r\n"
				+ "        <td>276082</td>\r\n"
				+ "        <td>133</td>\r\n"
				+ "        <td>96.24</td>\r\n"
				+ "        <td>95.79</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1117</td>\r\n"
				+ "        <td>276770</td>\r\n"
				+ "        <td>134</td>\r\n"
				+ "        <td>93.28</td>\r\n"
				+ "        <td>95.62</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1118</td>\r\n"
				+ "        <td>278261</td>\r\n"
				+ "        <td>135</td>\r\n"
				+ "        <td>94.07</td>\r\n"
				+ "        <td>95.63</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>1119</td>\r\n"
				+ "        <td>277348</td>\r\n"
				+ "        <td>131</td>\r\n"
				+ "        <td>95.42</td>\r\n"
				+ "        <td>95.63</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2101</td>\r\n"
				+ "        <td>250389</td>\r\n"
				+ "        <td>116</td>\r\n"
				+ "        <td>93.10</td>\r\n"
				+ "        <td>97.08</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2102</td>\r\n"
				+ "        <td>249361</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>93.16</td>\r\n"
				+ "        <td>97.07</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2103</td>\r\n"
				+ "        <td>248080</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>92.31</td>\r\n"
				+ "        <td>97.01</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2104</td>\r\n"
				+ "        <td>249519</td>\r\n"
				+ "        <td>116</td>\r\n"
				+ "        <td>93.97</td>\r\n"
				+ "        <td>97.20</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2105</td>\r\n"
				+ "        <td>248910</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>93.16</td>\r\n"
				+ "        <td>97.19</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2106</td>\r\n"
				+ "        <td>249358</td>\r\n"
				+ "        <td>119</td>\r\n"
				+ "        <td>92.44</td>\r\n"
				+ "        <td>97.16</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2107</td>\r\n"
				+ "        <td>249622</td>\r\n"
				+ "        <td>118</td>\r\n"
				+ "        <td>92.37</td>\r\n"
				+ "        <td>97.12</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2108</td>\r\n"
				+ "        <td>250222</td>\r\n"
				+ "        <td>119</td>\r\n"
				+ "        <td>92.44</td>\r\n"
				+ "        <td>97.04</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2109</td>\r\n"
				+ "        <td>251525</td>\r\n"
				+ "        <td>116</td>\r\n"
				+ "        <td>95.69</td>\r\n"
				+ "        <td>97.04</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2110</td>\r\n"
				+ "        <td>251130</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>94.87</td>\r\n"
				+ "        <td>97.24</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2111</td>\r\n"
				+ "        <td>251885</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>94.02</td>\r\n"
				+ "        <td>97.18</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2112</td>\r\n"
				+ "        <td>253172</td>\r\n"
				+ "        <td>117</td>\r\n"
				+ "        <td>94.87</td>\r\n"
				+ "        <td>97.17</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2113</td>\r\n"
				+ "        <td>255131</td>\r\n"
				+ "        <td>118</td>\r\n"
				+ "        <td>94.07</td>\r\n"
				+ "        <td>97.11</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2114</td>\r\n"
				+ "        <td>254758</td>\r\n"
				+ "        <td>119</td>\r\n"
				+ "        <td>91.60</td>\r\n"
				+ "        <td>97.09</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2115</td>\r\n"
				+ "        <td>257279</td>\r\n"
				+ "        <td>120</td>\r\n"
				+ "        <td>94.17</td>\r\n"
				+ "        <td>97.05</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2116</td>\r\n"
				+ "        <td>256711</td>\r\n"
				+ "        <td>119</td>\r\n"
				+ "        <td>95.80</td>\r\n"
				+ "        <td>97.27</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2117</td>\r\n"
				+ "        <td>258605</td>\r\n"
				+ "        <td>120</td>\r\n"
				+ "        <td>94.17</td>\r\n"
				+ "        <td>97.24</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2118</td>\r\n"
				+ "        <td>259412</td>\r\n"
				+ "        <td>120</td>\r\n"
				+ "        <td>94.17</td>\r\n"
				+ "        <td>97.28</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>1</td>\r\n"
				+ "        <td>2119</td>\r\n"
				+ "        <td>260021</td>\r\n"
				+ "        <td>121</td>\r\n"
				+ "        <td>93.39</td>\r\n"
				+ "        <td>97.36</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "        <td>0.00</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "    <h3><a href=\"Mismatch.htm\">Mismatch Graphs\r\n"
				+ "   </a></h3>\r\n"
				+ "  </body>\r\n"
				+ "</html>"
				);
	}
	
	public static final PropertyFileValue getPositionFile() {
		return PropertyFileValueFactory.getRandomPropertyFileValue("A005R4G-A1_S25.summary.csv",
				"Resequencing Summary Report\r\n"
				+ "Note: PCR duplicate reads are not removed from statistics. Results are not directly comparable to Picard metrics.\r\n"
				+ "\r\n"
				+ "Sample ID,A005R4G_A1\r\n"
				+ "Sample Name,A005R4G_A1\r\n"
				+ "Runfolder,D:\\CEA-CNRGH\\201103_MISEQ2_0189_000000000-J98GY\r\n"
				+ "Reference Genome,Homo sapiens (UCSC hg19)\r\n"
				+ "Paired End,True\r\n"
				+ "Diversity,48702832\r\n"
				+ "Total PF reads,174680\r\n"
				+ "Total aligned read 1,84066\r\n"
				+ "Total aligned read 2,83935\r\n"
				+ "Percent aligned read 1,96.3%\r\n"
				+ "Percent aligned read 2,96.1%\r\n"
				+ "Percent duplicate paired reads,0.1%\r\n"
				+ "Total PF bases,13275680\r\n"
				+ "Total PF bases read 1,6637840\r\n"
				+ "Total PF bases read 2,6637840\r\n"
				+ "Percent Q30 bases,98.6%\r\n"
				+ "Percent Q30 bases read 1,99.1%\r\n"
				+ "Percent Q30 bases read 2,98.1%\r\n"
				+ "Total aligned bases read 1,6382396\r\n"
				+ "Total aligned bases read 2,6368954\r\n"
				+ "Percent aligned bases read 1,96.2%\r\n"
				+ "Percent aligned bases read 2,95.9%\r\n"
				+ "Mismatch rate read 1,0.29%\r\n"
				+ "Mismatch rate read 2,0.33%\r\n"
				+ "Mean coverage,0.0\r\n"
				+ "Fragment length median,365\r\n"
				+ "Fragment length min,127\r\n"
				+ "Fragment length max,671\r\n"
				+ "Fragment length SD,81\r\n"
				+ ""
				);
	}

}
