package fr.cea.ig.ngl.test.dao.api;

import static fr.cea.ig.play.test.TestAssertions.assertNotEmpty;

import org.junit.Test;

import controllers.protocols.api.ProtocolsSearchForm;
import fr.cea.ig.ngl.dao.protocols.ProtocolsAPI;
import fr.cea.ig.ngl.test.dao.api.factory.QueryMode;
import fr.cea.ig.ngl.test.dao.api.factory.RenderMode;
import fr.cea.ig.ngl.test.dao.api.factory.TestListFormWrapperFactory;
import fr.cea.ig.ngl.test.resource.RApplication;
import fr.cea.ig.test.APIRef;
import models.laboratory.protocol.instance.Protocol;

public class ProtocolsAPITest {
	
	private static final play.Logger.ALogger logger = play.Logger.of(ProtocolsAPITest.class);
	
	//Tested API
	private static APIRef<ProtocolsAPI> api = APIRef.protocol;

	/* There are no restrictive tests here because Protocols are generated by NGL-Data. 
	 * Only check if any Protocols have been defined.
	 */
	
	@Test
	public void allTest() throws Exception {
		logger.debug("All test");
		RApplication.contextResource.accept((context) -> {
			assertNotEmpty(api.get().all());
		});
	}
	
	@Test
	public void listTest() throws Exception {
		logger.debug("List test");
		RApplication.contextResource.accept((context) -> {
            Iterable<Protocol> protos = api.get().listObjects(new TestListFormWrapperFactory<Protocol>().wrapping()
                                                                                                        .apply(new ProtocolsSearchForm(), 
                                                                                                               QueryMode.MONGOJACK, 
                                                                                                               RenderMode.LIST));
            assertNotEmpty(protos);
		});
	}
	
}
