#created on: Jul 7, 2014
package birds

import java.util.Date;
import java.text.SimpleDateFormat;

rule "Define variable lineParmeter for sendReleaseXML specification"
	@BirdsRule(fsRule)
	dialect 'java'
	salience 300
	no-loop
    when
       $treatSpec : TreatmentSpecification(name=="sendReleaseXML", project.name=="SRA")
       $job : Job()
    then
       Logger log = Logger.getLogger("ngl.sub.rules");
       log.debug("Set parameter for spec sendReleaseXML");
       $job.setParameterValue("xmlSubmission",$job.getParameterValue("xmlSubmission").getValue().replace("%xmlSubmission%","submission.xml"));
      // updateParameterXML("xmlSubmission",$job, "releaseToSend");
       $job.setParameterValue("listAC",$job.getParameterValue("listAC").getValue().replace("%submissionCode%",$job.getUniqueJobResource("releaseToSend").getProperty("code")));
       SimpleDateFormat dt = new SimpleDateFormat("yyyyMMddhhmm");
       String dateSubmission = dt.format(new Date());
       $job.setParameterValue("listAC",$job.getParameterValue("listAC").getValue().replace("%submissionDate%",dateSubmission));
       $job.setParameterValue("OptionCD",$job.getParameterValue("OptionCD").getValue().replace("%submissionDirectory%",$job.getUniqueJobResource("releaseToSend").getProperty("submissionDirectory")));
	
end

rule "POST DONE EXECUTION of sendReleaseXML : File release results operation"
	@BirdsRule( ExecutionService )
	dialect 'java'
	salience 200
	when
		$executionService : ExecutionService( status == ExecutionService.POST_JOB_EXECUTION_STATUS)
		$job : Job( treatmentSpecification!=null, treatmentSpecification.name == "sendReleaseXML", treatmentSpecification.project.name == "SRA", executionState == Job.DONE_STATUS )
	then
		Logger log = Logger.getLogger("ngl.sub.rules");
		//Call service treatment AC files results 
		JobResource jobResource = $job.getUniqueJobResource("releaseToSend");
		String codeSubmission = jobResource.getProperty("code");
		String studyAccession = jobResource.getProperty("studyAccession");
		String studyCode = jobResource.getProperty("studyCode");
		String creationUser = jobResource.getProperty("creationUser");
		String pathRelease = jobResource.getProperty("submissionDirectory")+File.separator+$job.getParameterValue("listAC").getValue();
		//File fileAC = new File(pathAC);
		log.debug("path release="+pathRelease);
		log.debug("Call treatment File Release "+pathRelease+" / "+codeSubmission+" / "+studyAccession+" / "+studyCode+" / "+creationUser);
		boolean ebiSuccess = false;
		try{
			ebiSuccess = SubmissionServicesFactory.getInstance().treatmentFileRelease(pathRelease, codeSubmission, studyAccession, studyCode, creationUser);
		}catch(Exception e){
			$job.setExecutionState(Job.ERROR_STATUS);
			$job.setProperty("Exception",e.getMessage());
		}
		JSONDevice jsonDevice = new JSONDevice();
		if(ebiSuccess){
			jsonDevice.httpPut(ProjectProperties.getProperty("server")+"/sra/submissions/"+codeSubmission+"/state", "{\"code\":\"F-SUB\"}", "bot");
		}else{
			jsonDevice.httpPut(ProjectProperties.getProperty("server")+"/sra/submissions/"+codeSubmission+"/state", "{\"code\":\"FE-SUB-R\"}", "bot");
			$job.setExecutionState(Job.ERROR_STATUS);
		}
end

