//FDS 13/11/2019
package rules

/* decommenter en 2.9.5
rule "Check sampleAliquoteCode pattern"
	@nglSQ( validations )
	dialect "java"
	salience 1000
	no-loop
    when
    	$contextValidation:ContextValidation()
    	Container($code:code)
    	Content(properties != null, $sampleAliquoteCode:properties.get("sampleAliquoteCode"), $sampleAliquoteCode != null )
	then
		//Check sampleAliquoteCode patterns
		//PB....   
		Pattern p1 = Pattern.compile("[A-Z,0-9]{7}", Pattern.DOTALL);                  // pattern de tube 
		Pattern p2 = Pattern.compile("[A-Z,0-9]{7}_[A-H][0-9]{1,2}", Pattern.DOTALL);  // pattern de puit de plaque
		
		Matcher m1 = p1.matcher($sampleAliquoteCode.value.toString());
		Matcher m2 = p2.matcher($sampleAliquoteCode.value.toString());
			
		if ( ! m1.matches() && ! m2.matches() ){
		//if( ! p1.matcher($sampleAliquoteCode.value).matches() && ! p2.matcher($sampleAliquoteCode.value).matches() ) {
			Logger.debug("Check sampleAliquoteCode pattern :'"+ $sampleAliquoteCode.value +"' not match [A-Z,0-9]{7} nor [A-Z,0-9]{7}_[A-H][0-9]{1,2}");
			// utiliser plutot un message stocké dans un fichier "messages" !!
			$contextValidation.addErrors("sampleAliquotCode", $sampleAliquoteCode.value +" ne correspond ni a un barcode de tube ni un barcode de plaque");
		}
	end
*/