//created on: Nov 21, 2013
package rules

//list any import classes here.
import models.laboratory.container.instance.Content;
import models.laboratory.container.instance.Container;
import models.laboratory.container.instance.ContainerSupport;
import models.laboratory.run.instance.Run;
import models.laboratory.run.instance.Lane;
import models.laboratory.run.instance.Analysis;
import models.laboratory.run.instance.ReadSetProperties;
import models.laboratory.run.instance.ReadSet;
import models.laboratory.run.instance.Treatment;
import models.laboratory.sample.instance.Sample;
import models.utils.InstanceConstants;
import models.laboratory.common.instance.PropertyValue;
import models.laboratory.common.instance.property.PropertySingleValue;
import models.laboratory.common.instance.property.PropertyFileValue;
import models.laboratory.common.instance.property.PropertyObjectListValue;
import models.laboratory.common.instance.property.PropertyObjectValue;
import models.laboratory.common.instance.property.PropertyListValue;
import models.laboratory.common.instance.TraceInformation;
import validation.ContextValidation;
import models.utils.InstanceHelpers;
import models.utils.InstanceConstants;
import fr.cea.ig.MongoDBDAO;
import play.Logger;
import java.util.*;
import java.text.DecimalFormat;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.mongojack.DBQuery;
import org.mongojack.DBUpdate;
import com.mongodb.BasicDBObject;

import lims.services.ILimsRunServices;
import play.api.modules.spring.Spring;
import org.apache.commons.lang3.StringUtils;
