package ngl.data;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Map;

import javax.sql.DataSource;

import fr.cea.ig.lfw.utils.Iterables;
import fr.cea.ig.lfw.utils.ZenIterable;
import fr.cea.ig.ngl.utils.HashMapBuilder;
import nglapps.IApplicationData;

// 
public abstract class NGLDataDBBuilder {
	
	private static final play.Logger.ALogger logger = play.Logger.of(NGLDataDBBuilder.class);
	
	private static final Map<String,NGLDataDBBuilder> dbBuilders = //new HashMap<>();
			new HashMapBuilder<String,NGLDataDBBuilder>()
			.put("HSQL Database Engine", new HSSQLDBBuilder())
			.put("MySQL",                new MySQLDBBuilder())
			.asMap();
	
	public static void rebuildDB(DataSource dataSource,  IApplicationData ad) {
		try {
			DatabaseMetaData dm = dataSource.getConnection().getMetaData();
			String productName = dm.getDatabaseProductName();
			if (productName == null)
				throw new Exception("cannot identify database through product name (no name found)");
			NGLDataDBBuilder rp = dbBuilders.get(productName);
			if (rp == null)
				throw new Exception("no repopulator defined for '" + productName + "'");
			rp.rebuildDB(dataSource);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}
	
	// We ignore table drop errors as the table may no exist.
	// We expect the the system to fail elsewhere if there is a "real"
	// problem.
	protected void dropTables(DataSource ds, Iterable<String> ts) {
		for (String tn : ts) {
			try (Connection connection = ds.getConnection(); Statement statement = connection.createStatement()) {
				String sql = "drop table " + tn;
				statement.executeUpdate(sql);
				logger.info("dropped table '{}'", tn);
			} catch (Exception e) {
				logger.info("table not dropped {} : {}",tn,e.getMessage());
			}
		}		
	}
	
	public abstract void rebuildDB(DataSource ds) throws Exception;
	
	static class MySQLDBBuilder extends NGLDataDBBuilder {
		@SuppressWarnings("hiding")
		private static final play.Logger.ALogger logger = play.Logger.of(MySQLDBBuilder.class);
		// Load the schema, drop the tables and run the full script.
		@Override
		public void rebuildDB(DataSource ds) throws Exception {
			NGLSchemaInfo nsi = new NGLSchemaInfo();
			Iterable<String> reverseDeps = nsi.getReverseDependentNames();
			Iterable<String> deps        = nsi.getDependentNames();
			dropTables(ds,reverseDeps);
			for (String tn 	: deps) {
				CreateTableParser p = nsi.getParser(tn);
				try (Connection connection = ds.getConnection();
						Statement statement = connection.createStatement()) {
					logger.info("creating table '{}'", tn);
					// logger.debug("creating tbale {} : {}",sql);
					statement.executeUpdate(p.mySQL);
				}
			}
		}		
	}
	
	static class HSSQLDBBuilder extends NGLDataDBBuilder {
		@SuppressWarnings("hiding")
		private static final play.Logger.ALogger logger = play.Logger.of(HSSQLDBBuilder.class);
		// Load the schema, create database using the HSQL definitions.
		@Override
		public void rebuildDB(DataSource ds) throws Exception {
			//DataSource ds = db.getDataSource();
			NGLSchemaInfo nsi = new NGLSchemaInfo();
			Iterable<String> reverseDeps = nsi.getReverseDependentNames();
			Iterable<String> deps        = nsi.getDependentNames();
			dropTables(ds,reverseDeps);
			// Run table creation in dependency order
			for (String tn : deps) {
				// System.out.println("  - " + tn + " " + asString(deps.get(tn)));
				// CreateTableParser p = parsers.get(tn);
				CreateTableParser p = nsi.getParser(tn);
				ZenIterable<String> columns = 
						Iterables.map(p.getColumns(), 
								c -> c.getName() + " " + sqlType(c.getType(),c.getSize())
								+ (c.notNull() ? " not null" : " null")
								// + (c.increment() ? " identity" : ""));
								+ (c.increment() ? " generated by default as identity (start with 100)" : ""));
				ZenIterable<String> constraints =
						Iterables.map(p.getConstraints(), c -> sqlConstraint(c));
				String sql =
						Iterables.flatten(Arrays.asList(columns,constraints))
						.surround("create table " + tn + " (\n",",\n", "\n)")
						.asString();
				// System.out.println("## SQL for " + tn + "\n" + sql);
				try (Connection connection = ds.getConnection();
						Statement statement = connection.createStatement()) {
					logger.info("creating table '{}'", tn);
					// logger.debug("{}",sql);
					statement.executeUpdate(sql);
				}
			}
		}	
		
		public static String sqlConstraint(CreateTableParser.Constraint c) {
			if (c instanceof CreateTableParser.PK) {
				CreateTableParser.PK pk = ( CreateTableParser.PK)c;
				return "primary key " + asString(pk.getKey());
			} else if (c instanceof CreateTableParser.FK) {
				CreateTableParser.FK fk = (CreateTableParser.FK)c;
				return "foreign key " + asString(fk.key) + " references " + fk.tableName + " " + asString(fk.fkey); 
			} else if (c instanceof CreateTableParser.Unique) {
				CreateTableParser.Unique u = (CreateTableParser.Unique)c;
				return "unique " + asString(u.key);
			} else {
				throw new RuntimeException("not handled " + c);
			}
		}

		public static String sqlType(String t, String p) {
			switch (t.toLowerCase()) {
			case "tinyint"  : return "tinyint";
			case "smallint" : return "smallint";
			case "int"      : return "int";
			case "bigint"   : return "bigint";
			//		case "bigint"   : return "int";
			case "varchar"  : return "varchar(" + p + ")";
			//		case "text"     : return "text";
			case "text"     : return "varchar(255)";
			}
			throw new RuntimeException("unhandled type '" + t + "'");
		}
		private static String asString(Iterable<String> i) {
			return Iterables.zen(i).surround("(", ",", ")").asString();
		}

	}
	
}
