//created on: Nov 21, 2013
package rules

//list any import classes here.
import models.laboratory.container.instance.Content;
import models.laboratory.container.instance.Container;
import models.laboratory.container.instance.ContainerSupport;
import models.laboratory.run.instance.Run;
import models.laboratory.run.instance.Lane;
import models.laboratory.run.instance.Treatment;
import models.laboratory.run.instance.ReadSet;
import models.laboratory.alert.instance.Alert;
import models.laboratory.sample.instance.Sample;
import models.utils.InstanceConstants;
import models.laboratory.common.instance.PropertyValue;
import models.laboratory.common.instance.property.PropertySingleValue;
import models.laboratory.common.instance.property.PropertyObjectListValue;
import models.laboratory.common.instance.property.PropertyListValue;
import models.laboratory.common.instance.property.PropertyObjectValue;
import fr.cea.ig.MongoDBDAO;
import alert.AlertSAVInfo;
import mail.MailServices;
import play.Logger;
import play.Play;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.TreeSet;
import java.util.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Arrays;
import java.util.Date;
import java.text.DecimalFormat;
import org.mongojack.DBQuery;
import org.mongojack.DBUpdate;
import org.apache.commons.lang3.StringUtils;

import validation.ContextValidation;
import play.data.validation.ValidationError;
import models.laboratory.common.instance.TraceInformation;
import models.utils.InstanceHelpers;
import models.utils.InstanceConstants;